[package]
name = "async_pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
join_me_maybe = "0.1.0"

[dev-dependencies]
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
